from src.malignant.exhaustive_linkage import qualify_exhaustive_candidate as q
def test_same_patient_rejected(): assert q()=='MALIGNANT_NOT_OBSERVABLE'
def test_same_sample_rejected(): assert q()=='MALIGNANT_NOT_OBSERVABLE'
def test_same_tumour_rejected(): assert q()=='MALIGNANT_NOT_OBSERVABLE'
def test_same_cluster_rejected(): assert q()=='MALIGNANT_NOT_OBSERVABLE'
def test_same_clone_without_mapping_rejected(): assert q(malignant_validated=True)=='MALIGNANT_PARTIAL'
def test_genotype_without_rna_barcode_rejected(): assert q(malignant_validated=True,public_mapping=False)=='MALIGNANT_PARTIAL'
def test_cnv_without_mapping_rejected(): assert q(cnv_supported=True)=='MALIGNANT_PARTIAL'
def test_cnv_without_reference_rejected(): assert q(same_cell=True,public_mapping=True,malignant_validated=True,cnv_supported=True,reference_available=False,second_audit_passed=True)=='MALIGNANT_PARTIAL'
def test_publication_only_partial(): assert q(publication_only=True)=='MALIGNANT_PARTIAL'
def test_treatment_rejected(): assert q(same_cell=True,public_mapping=True,malignant_validated=True,treatment_used=True)=='MALIGNANT_NOT_OBSERVABLE'
def test_outcome_rejected(): assert q(same_cell=True,public_mapping=True,malignant_validated=True,outcome_used=True)=='MALIGNANT_NOT_OBSERVABLE'
def test_validated_same_cell_e5(): assert q(same_cell=True,public_mapping=True,malignant_validated=True,direct_ground_truth=True,second_audit_passed=True)=='MALIGNANT_GROUND_TRUTH'
def test_reproducible_same_cell_cnv_e4(): assert q(same_cell=True,public_mapping=True,malignant_validated=True,cnv_supported=True,reference_available=True,second_audit_passed=True)=='MALIGNANT_REPRODUCIBLE_INFERENCE'
def test_missing_mapping_blocks(): assert q(same_cell=True,malignant_validated=True,second_audit_passed=True)=='MALIGNANT_PARTIAL'
def test_second_audit_failure_downgrades(): assert q(same_cell=True,public_mapping=True,malignant_validated=True,direct_ground_truth=True,second_audit_passed=False)=='MALIGNANT_PARTIAL'
def test_unknown_never_verified(): assert q(public_mapping=False,second_audit_passed=False)=='MALIGNANT_NOT_OBSERVABLE'
def test_public_raw_without_mapping_insufficient(): assert q(malignant_validated=True,public_mapping=False)=='MALIGNANT_PARTIAL'
def test_public_matrix_without_genomic_link_insufficient(): assert q()== 'MALIGNANT_NOT_OBSERVABLE'
