from src.malignant.rna_clone_linkage import *
def test_same_patient_not_same_cell(): assert qualify_rna_clone_linkage(clone_assigned=True)=='MALIGNANT_PARTIAL'
def test_same_sample_not_same_cell(): assert qualify_rna_clone_linkage(clone_assigned=True)=='MALIGNANT_PARTIAL'
def test_same_tumour_not_mapping(): assert clone_observability()== 'NOT_AVAILABLE'
def test_cluster_not_genotype(): assert qualify_rna_clone_linkage(clone_assigned=True)=='MALIGNANT_PARTIAL'
def test_publication_labels_partial(): assert qualify_rna_clone_linkage(clone_assigned=True)=='MALIGNANT_PARTIAL'
def test_barcodes_without_mapping_partial(): assert qualify_rna_clone_linkage(public_inputs=True)=='MALIGNANT_NOT_OBSERVABLE'
def test_similar_barcodes_insufficient(): assert qualify_rna_clone_linkage(clone_assigned=True,public_inputs=True)=='MALIGNANT_PARTIAL'
def test_cnv_without_mapping_partial(): assert clone_observability(method_documented=True)=='PARTIAL'
def test_genotype_without_barcode_partial(): assert qualify_rna_clone_linkage(clone_assigned=True)=='MALIGNANT_PARTIAL'
def test_epithelial_not_ground_truth(): assert qualify_rna_clone_linkage(malignant_validated=False)=='MALIGNANT_NOT_OBSERVABLE'
def test_tumour_label_not_identity(): assert qualify_rna_clone_linkage(malignant_validated=False)=='MALIGNANT_NOT_OBSERVABLE'
def test_treatment_leakage_closed(): assert qualify_rna_clone_linkage(treatment_used=True)=='MALIGNANT_NOT_OBSERVABLE'
def test_outcome_leakage_closed(): assert qualify_rna_clone_linkage(outcome_used=True)=='MALIGNANT_NOT_OBSERVABLE'
def test_future_assignment_not_admitted(): assert qualify_rna_clone_linkage(second_audit_passed=False,same_cell=True)=='MALIGNANT_PARTIAL'
def test_controlled_not_public(): assert qualify_rna_clone_linkage(controlled_metadata=True)=='MALIGNANT_NOT_OBSERVABLE'
def test_e4_requires_public_method(): assert qualify_rna_clone_linkage(same_cell=True,malignant_validated=True,clone_assigned=True,second_audit_passed=True)!='MALIGNANT_REPRODUCIBLE_INFERENCE'
def test_e5_requires_validation(): assert qualify_rna_clone_linkage(same_cell=True,public_inputs=True,clone_assigned=True,direct_ground_truth=True,second_audit_passed=True)!='MALIGNANT_GROUND_TRUTH'
def test_missing_mapping_closed(): assert clone_observability()== 'NOT_AVAILABLE'
def test_valid_e5(): assert qualify_rna_clone_linkage(same_cell=True,public_inputs=True,malignant_validated=True,clone_assigned=True,direct_ground_truth=True,second_audit_passed=True)=='MALIGNANT_GROUND_TRUTH'
def test_valid_e4(): assert qualify_rna_clone_linkage(same_cell=True,public_inputs=True,method_documented=True,malignant_validated=True,clone_assigned=True,second_audit_passed=True)=='MALIGNANT_REPRODUCIBLE_INFERENCE'
def test_clone_not_lineage(): assert qualify_rna_clone_linkage(same_cell=True,public_inputs=True,method_documented=True,malignant_validated=True,clone_assigned=True,second_audit_passed=True)=='MALIGNANT_REPRODUCIBLE_INFERENCE'
def test_within_clone_not_lineage(): assert clone_observability(cell_mapping=True,public_inputs=True,method_documented=True)=='VERIFIED'
def test_missing_repeated_samples_not_selection(): assert clone_observability(cell_mapping=True,public_inputs=True,method_documented=True)=='VERIFIED'
def test_missing_clone_blocks_selection(): assert clone_observability()== 'NOT_AVAILABLE'
def test_phase5_closed_even_found(): assert True
