from src.malignant.observability import qualify_observability, phase5_eligible
def test_epithelial_only_is_partial(): assert qualify_observability(epithelial_only=True)=='MALIGNANT_PARTIAL'
def test_tumour_sample_is_not_cell_ground_truth(): assert qualify_observability()=='MALIGNANT_NOT_OBSERVABLE'
def test_response_cannot_promote(): assert qualify_observability(cnv_reproducible=True,outcome_used=True)=='MALIGNANT_NOT_OBSERVABLE'
def test_cnv_is_not_ground_truth(): assert qualify_observability(cnv_reproducible=True)=='MALIGNANT_PARTIAL'
def test_downloadable_annotation_can_be_reproducible(): assert qualify_observability(cell_metadata=True,author_annotation=True,author_annotation_type='malignant',author_annotation_validated=True,author_annotation_provenance='E4')=='MALIGNANT_REPRODUCIBLE_INFERENCE'
def test_partial_does_not_unlock(): assert phase5_eligible('MALIGNANT_PARTIAL') is False
def test_generic_author_annotation_cannot_promote(): assert qualify_observability(cell_metadata=True,author_annotation=True)=='MALIGNANT_PARTIAL'
def test_epithelial_annotation_is_partial(): assert qualify_observability(cell_metadata=True,author_annotation=True,author_annotation_type='epithelial')=='MALIGNANT_PARTIAL'
def test_tumour_like_annotation_is_partial(): assert qualify_observability(cell_metadata=True,author_annotation=True,author_annotation_type='tumour_like')=='MALIGNANT_PARTIAL'
def test_unvalidated_malignant_annotation_is_partial(): assert qualify_observability(cell_metadata=True,author_annotation=True,author_annotation_type='malignant')=='MALIGNANT_PARTIAL'
def test_validated_malignant_annotation_can_qualify(): assert qualify_observability(cell_metadata=True,author_annotation=True,author_annotation_type='malignant',author_annotation_validated=True,author_annotation_provenance='E4')=='MALIGNANT_REPRODUCIBLE_INFERENCE'
def test_cnv_requires_explicit_pipeline_support(): assert qualify_observability(cell_metadata=True,cnv_reproducible=True)=='MALIGNANT_PARTIAL'
def test_supported_cnv_is_inference_not_ground_truth(): assert qualify_observability(cell_metadata=True,cnv_reproducible=True,cnv_pipeline_supported=True)=='MALIGNANT_REPRODUCIBLE_INFERENCE'
def test_treatment_cannot_promote(): assert qualify_observability(cell_metadata=True,author_annotation=True,author_annotation_type='malignant',author_annotation_validated=True,author_annotation_provenance='E4',treatment_used=True)=='MALIGNANT_NOT_OBSERVABLE'
