"""Minimal observation-model protocol; no deep decoder is implemented."""
from abc import ABC, abstractmethod
class ObservationModel(ABC):
    @abstractmethod
    def fit(self, latent_state, observed, modality, **kwargs): ...
    @abstractmethod
    def encode(self, observed, modality, **kwargs): ...
    @abstractmethod
    def decode(self, latent_state, modality, **kwargs): ...
    @abstractmethod
    def likelihood(self, latent_state, observed, modality, **kwargs): ...
    def missingness(self, observed, modality): return {"modality":modality,"missing":observed is None}
